### ISSUE TITLE
Saving and loading issues when transforms are attributes in a class

### ISSUE THREAD

**Issue by eramdiaz** [lf1-io/padl#256] opened 2021-11-15 17:55 UTC
## 🐞 Bug

When a `Transform` is an attribute of a class and it saved inside it, an `OSError: source code not available` error is got when loading it.

1. Code: 
```
@transform
def times_two(x):
    return x * 2

@transform
class MyClass:
    def __init__(self, a): 
        self.a = a
    def __call__(self, x):  
        return self.a + x

@transform
class Test:
    def __init__(self):
        self.t2 = MyClass(6)
        self.t2.pd_save('t2.padl', force_overwrite=True)
        times_two.pd_save('t4.padl', force_overwrite=True)

t = Test()
t4 = load('t4.padl') # This works
t2 = load('t2.padl')
```
2. Error: 
![Screenshot from 2021-11-15 18-53-42](https://user-images.githubusercontent.com/78182182/141830579-9c6d3140-1ea3-4d18-a63b-4c3740898757.png)

**Comment by sjrl** [comment] 2021-11-16 07:40
@eramdiaz Could you update the above code so that it can be run to reproduce the error? It looks like there are a few typos.

**Comment by sjrl** [comment] 2021-11-16 07:55
Looking into this it looks like the issue results from saving a transform that includes in it's source code a `pd_save` call. So when calling `self.t2.pd_save('t2.padl', force_overwrite=True)` the resulting `transforms.py` file looks like
```python
from padl import transform


@transform
class MyClass:
    def __init__(self, a): 
        self.a = a
    def __call__(self, x):  
        return self.a + x


@transform
def times_two(x):
    return x * 2


@transform
class Test:
    def __init__(self):
        self.t2 = MyClass(6)
        self.t2.pd_save('t2.padl', force_overwrite=True)
        times_two.pd_save('t4.padl', force_overwrite=True)


_pd_main = Test()
```
so when you try to load `t2 = load('t2.padl')` you again call `pd_save` which I think causes the issue.

**Comment by sjrl** [comment] 2021-11-16 08:03
@eramdiaz Could you explain the scenario in which you would like to call the `pd_save` function from within in a `class` or a `transform`?

**Comment by jasonkhadka** [comment] 2021-11-16 08:42
This could though may have other problems, as it would not be possible to ensure that every source code will not have `pd_save`. 
Perhaps, we should disable `pd_save` when a `load` is called? To ensure no overwriting is done is attempted until safely loaded.

**Comment by eramdiaz** [comment] 2021-11-16 08:57
At the moment there must be ways to overcome this problem, but if there are two `Transform` and one is only used or makes sense inside other, we could want to use this functionality. For example, if we had a tokenizer and a padding we might want to include the tokenizer call inside the padding call, and for that we need to save the first.

**Comment by sjrl** [comment] 2021-11-16 09:07
> At the moment there must be ways to overcome this problem, but if there are two `Transform` and one is only used or makes sense inside other, we could want to use this functionality. For example, if we had a tokenizer and a padding we might want to include the tokenizer call inside the padding call, and for that we need to save the first. I consider this is a desirable behaviour.

Hmm I'm not sure I understand. Could you not either 1) have the tokenizer feed into the pad transform `t = tokenizer >> padding` or 2) you create a single class transform that does both `tokenize_and_pad` without inheriting transforms? 

I understand that you could also make a new transform that inherits the transforms `tokenize` and `padding`, but then you would probably save the parent class, not the individual transforms inside right?

**Comment by sjrl** [comment] 2021-11-16 09:10
> This could though create other problems, as it would not be possible to ensure that every source code will not have `pd_save`. Perhaps, we should disable `pd_save` when a `load` is called? To ensure no overwriting is done is attempted until safely loaded.

I agree that some sort of check or warning should be raised in this case. I'm not sure if disabling by itself is enough, because the loaded transform would not act in the same way as when the original transform was created.

**Comment by sjrl** [comment] 2021-11-16 09:15
@eramdiaz If you think it's worth solving this for Phase 2 please add it to the project board.

**Comment by jasonkhadka** [comment] 2021-11-16 09:17
> > This could though create other problems, as it would not be possible to ensure that every source code will not have `pd_save`. Perhaps, we should disable `pd_save` when a `load` is called? To ensure no overwriting is done is attempted until safely loaded.
> 
> I agree that some sort of check or warning should be raised in this case. I'm not sure if disabling by itself is enough, because the loaded transform would not act in the same way as when the original transform was created which could be confusing.

yup, i agree, but just disabling `pd_save` inside load should not create an problem (unless there is certain functionality that relies on things written to disc). We can handle this with some kind of context manager. 
```
with stage=save
     do things where 'pd_save' is an empty function
```

This will keep everything same after loading, but just for loading part make `pd_save` empty function

**Comment by eramdiaz** [comment] 2021-11-16 09:24
This is related to my following error when creating a saving and loading test:
```
def test_save_and_load_1(self, tmp_path):
    self.try_transform_1.pd_save(tmp_path / 'test.padl')
    t1 = padl.load(tmp_path / 'test.padl')
    assert t1.infer_apply(4) == 1
```
where I get the following error when loading the `Transform`
![Screenshot from 2021-11-16 10-14-43](https://user-images.githubusercontent.com/78182182/141958132-0d5d7513-2f2b-471a-9197-683a8c0ba117.png)
:

Appareantly, it is interpreting `self` to be the `varname` of the `Transform` since it is being called like `self.try_transform_1.pd_save`.

**Comment by jasonkhadka** [comment] 2021-11-16 09:27
> This is related to my following error when creating a saving and loading test:
> 
> ```
> def test_save_and_load_1(self, tmp_path):
>     self.try_transform_1.pd_save(tmp_path / 'test.padl')
>     t1 = padl.load(tmp_path / 'test.padl')
>     assert t1.infer_apply(4) == 1
> ```
> 
> where I get the following error when loading the `Transform` ![Screenshot from 2021-11-16 10-14-43](https://user-images.githubusercontent.com/78182182/141958132-0d5d7513-2f2b-471a-9197-683a8c0ba117.png) :
> 
> Appareantly, it is interpreting `self` to be the `varname` of the `Transform` since it is being called like `self.try_transform_1.pd_save`.

Could you post the complete code with minimal reproducible example?

**Comment by wuhu** [comment] 2021-12-15 09:54
@eramdiaz are the two things really the same? If not, please open another issue with the second problem with some minimal reproducible example.

As for the first issue. I think it comes from a misunderstanding of how the saving works: If a transform contains another transform as an attribute, the latter will automatically be saved, there is no need to explicitly do that. Especially calling save inside the init will cause a loop. We could perhaps document this better, but I don't there's anything that needs to be fixed.

**Comment by wuhu** [comment] 2021-12-15 10:53
closing this, @eramdiaz to check if the second problem still occurs and if so open a new issue

**Closed by wuhu** 2021-12-15 10:53 UTC
Labels: bug
